// source: seekret/proto/api_gateway/api_gateway.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest', null, global);
goog.exportSymbol('proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse', null, global);
goog.exportSymbol('proto.seekret.api_gateway.WorkspaceEntry', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.seekret.api_gateway.WorkspaceEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.seekret.api_gateway.WorkspaceEntry.repeatedFields_, null);
};
goog.inherits(proto.seekret.api_gateway.WorkspaceEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.seekret.api_gateway.WorkspaceEntry.displayName = 'proto.seekret.api_gateway.WorkspaceEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.displayName = 'proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.displayName = 'proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.seekret.api_gateway.WorkspaceEntry.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.seekret.api_gateway.WorkspaceEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.seekret.api_gateway.WorkspaceEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.WorkspaceEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    baseDir: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bucketName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    endpoint: jspb.Message.getFieldWithDefault(msg, 3, ""),
    accessKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    secretKey: jspb.Message.getFieldWithDefault(msg, 5, ""),
    insecure: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    hostWhitelistList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.seekret.api_gateway.WorkspaceEntry}
 */
proto.seekret.api_gateway.WorkspaceEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.seekret.api_gateway.WorkspaceEntry;
  return proto.seekret.api_gateway.WorkspaceEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.seekret.api_gateway.WorkspaceEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.seekret.api_gateway.WorkspaceEntry}
 */
proto.seekret.api_gateway.WorkspaceEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBaseDir(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBucketName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndpoint(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccessKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecretKey(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInsecure(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addHostWhitelist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.seekret.api_gateway.WorkspaceEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.seekret.api_gateway.WorkspaceEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.WorkspaceEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseDir();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBucketName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEndpoint();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAccessKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSecretKey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getInsecure();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getHostWhitelistList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
};


/**
 * optional string base_dir = 1;
 * @return {string}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getBaseDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setBaseDir = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string bucket_name = 2;
 * @return {string}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getBucketName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setBucketName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string endpoint = 3;
 * @return {string}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getEndpoint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setEndpoint = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string access_key = 4;
 * @return {string}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getAccessKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setAccessKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string secret_key = 5;
 * @return {string}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getSecretKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setSecretKey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool insecure = 6;
 * @return {boolean}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getInsecure = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setInsecure = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * repeated string host_whitelist = 7;
 * @return {!Array<string>}
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.getHostWhitelistList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.setHostWhitelistList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.addHostWhitelist = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.seekret.api_gateway.WorkspaceEntry} returns this
 */
proto.seekret.api_gateway.WorkspaceEntry.prototype.clearHostWhitelistList = function() {
  return this.setHostWhitelistList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    workspace: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest;
  return proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkspace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkspace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string workspace = 1;
 * @return {string}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.prototype.getWorkspace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest} returns this
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationRequest.prototype.setWorkspace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    entry: (f = msg.getEntry()) && proto.seekret.api_gateway.WorkspaceEntry.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse;
  return proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.seekret.api_gateway.WorkspaceEntry;
      reader.readMessage(value,proto.seekret.api_gateway.WorkspaceEntry.deserializeBinaryFromReader);
      msg.setEntry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntry();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.seekret.api_gateway.WorkspaceEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional WorkspaceEntry entry = 1;
 * @return {?proto.seekret.api_gateway.WorkspaceEntry}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.getEntry = function() {
  return /** @type{?proto.seekret.api_gateway.WorkspaceEntry} */ (
    jspb.Message.getWrapperField(this, proto.seekret.api_gateway.WorkspaceEntry, 1));
};


/**
 * @param {?proto.seekret.api_gateway.WorkspaceEntry|undefined} value
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse} returns this
*/
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.setEntry = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse} returns this
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.clearEntry = function() {
  return this.setEntry(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.seekret.api_gateway.FetchWorkspaceConfigurationResponse.prototype.hasEntry = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.seekret.api_gateway);
