# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seekret/proto/api_gateway/api_gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+seekret/proto/api_gateway/api_gateway.proto\x12\x13seekret.api_gateway\"\x9b\x01\n\x0eWorkspaceEntry\x12\x10\n\x08\x62\x61se_dir\x18\x01 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x12\n\naccess_key\x18\x04 \x01(\t\x12\x12\n\nsecret_key\x18\x05 \x01(\t\x12\x10\n\x08insecure\x18\x06 \x01(\x08\x12\x16\n\x0ehost_whitelist\x18\x07 \x03(\t\"7\n\"FetchWorkspaceConfigurationRequest\x12\x11\n\tworkspace\x18\x01 \x01(\t\"Y\n#FetchWorkspaceConfigurationResponse\x12\x32\n\x05\x65ntry\x18\x01 \x01(\x0b\x32#.seekret.api_gateway.WorkspaceEntry2\x9f\x01\n\nApiGateway\x12\x90\x01\n\x1b\x46\x65tchWorkspaceConfiguration\x12\x37.seekret.api_gateway.FetchWorkspaceConfigurationRequest\x1a\x38.seekret.api_gateway.FetchWorkspaceConfigurationResponseB9Z7github.com/seek-ret/public-protobuf/protogo/api_gatewayb\x06proto3')



_WORKSPACEENTRY = DESCRIPTOR.message_types_by_name['WorkspaceEntry']
_FETCHWORKSPACECONFIGURATIONREQUEST = DESCRIPTOR.message_types_by_name['FetchWorkspaceConfigurationRequest']
_FETCHWORKSPACECONFIGURATIONRESPONSE = DESCRIPTOR.message_types_by_name['FetchWorkspaceConfigurationResponse']
WorkspaceEntry = _reflection.GeneratedProtocolMessageType('WorkspaceEntry', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEENTRY,
  '__module__' : 'seekret.proto.api_gateway.api_gateway_pb2'
  # @@protoc_insertion_point(class_scope:seekret.api_gateway.WorkspaceEntry)
  })
_sym_db.RegisterMessage(WorkspaceEntry)

FetchWorkspaceConfigurationRequest = _reflection.GeneratedProtocolMessageType('FetchWorkspaceConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHWORKSPACECONFIGURATIONREQUEST,
  '__module__' : 'seekret.proto.api_gateway.api_gateway_pb2'
  # @@protoc_insertion_point(class_scope:seekret.api_gateway.FetchWorkspaceConfigurationRequest)
  })
_sym_db.RegisterMessage(FetchWorkspaceConfigurationRequest)

FetchWorkspaceConfigurationResponse = _reflection.GeneratedProtocolMessageType('FetchWorkspaceConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHWORKSPACECONFIGURATIONRESPONSE,
  '__module__' : 'seekret.proto.api_gateway.api_gateway_pb2'
  # @@protoc_insertion_point(class_scope:seekret.api_gateway.FetchWorkspaceConfigurationResponse)
  })
_sym_db.RegisterMessage(FetchWorkspaceConfigurationResponse)

_APIGATEWAY = DESCRIPTOR.services_by_name['ApiGateway']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/seek-ret/public-protobuf/protogo/api_gateway'
  _WORKSPACEENTRY._serialized_start=69
  _WORKSPACEENTRY._serialized_end=224
  _FETCHWORKSPACECONFIGURATIONREQUEST._serialized_start=226
  _FETCHWORKSPACECONFIGURATIONREQUEST._serialized_end=281
  _FETCHWORKSPACECONFIGURATIONRESPONSE._serialized_start=283
  _FETCHWORKSPACECONFIGURATIONRESPONSE._serialized_end=372
  _APIGATEWAY._serialized_start=375
  _APIGATEWAY._serialized_end=534
# @@protoc_insertion_point(module_scope)
