# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seekret/proto/auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dseekret/proto/auth/auth.proto\x12\x16seekret.authentication\"7\n\x0b\x43redentials\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\"9\n\nJWTDetails\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"V\n\x13\x41uthenticateRequest\x12?\n\x12\x63lient_credentials\x18\x01 \x01(\x0b\x32#.seekret.authentication.Credentials\"K\n\x14\x41uthenticateResponse\x12\x33\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\".seekret.authentication.JWTDetails2s\n\x04\x41uth\x12k\n\x0c\x41uthenticate\x12+.seekret.authentication.AuthenticateRequest\x1a,.seekret.authentication.AuthenticateResponse\"\x00\x42\x32Z0github.com/seek-ret/public-protobuf/protogo/authb\x06proto3')



_CREDENTIALS = DESCRIPTOR.message_types_by_name['Credentials']
_JWTDETAILS = DESCRIPTOR.message_types_by_name['JWTDetails']
_AUTHENTICATEREQUEST = DESCRIPTOR.message_types_by_name['AuthenticateRequest']
_AUTHENTICATERESPONSE = DESCRIPTOR.message_types_by_name['AuthenticateResponse']
Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.authentication.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

JWTDetails = _reflection.GeneratedProtocolMessageType('JWTDetails', (_message.Message,), {
  'DESCRIPTOR' : _JWTDETAILS,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.authentication.JWTDetails)
  })
_sym_db.RegisterMessage(JWTDetails)

AuthenticateRequest = _reflection.GeneratedProtocolMessageType('AuthenticateRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATEREQUEST,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.authentication.AuthenticateRequest)
  })
_sym_db.RegisterMessage(AuthenticateRequest)

AuthenticateResponse = _reflection.GeneratedProtocolMessageType('AuthenticateResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATERESPONSE,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.authentication.AuthenticateResponse)
  })
_sym_db.RegisterMessage(AuthenticateResponse)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/seek-ret/public-protobuf/protogo/auth'
  _CREDENTIALS._serialized_start=57
  _CREDENTIALS._serialized_end=112
  _JWTDETAILS._serialized_start=114
  _JWTDETAILS._serialized_end=171
  _AUTHENTICATEREQUEST._serialized_start=173
  _AUTHENTICATEREQUEST._serialized_end=259
  _AUTHENTICATERESPONSE._serialized_start=261
  _AUTHENTICATERESPONSE._serialized_end=336
  _AUTH._serialized_start=338
  _AUTH._serialized_end=453
# @@protoc_insertion_point(module_scope)
