# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seekret/proto/auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seekret/proto/auth/auth.proto',
  package='seekret.auth',
  syntax='proto3',
  serialized_options=b'Z0github.com/seek-ret/public-protobuf/protogo/auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dseekret/proto/auth/auth.proto\x12\x0cseekret.auth\"=\n\x11\x43lientCredentials\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\"9\n\nJWTDetails\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"X\n\x19\x43lientAuthenticateRequest\x12;\n\x12\x63lient_credentials\x18\x01 \x01(\x0b\x32\x1f.seekret.auth.ClientCredentials\"G\n\x1a\x43lientAuthenticateResponse\x12)\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\x18.seekret.auth.JWTDetails2q\n\x04\x41uth\x12i\n\x12\x43lientAuthenticate\x12\'.seekret.auth.ClientAuthenticateRequest\x1a(.seekret.auth.ClientAuthenticateResponse\"\x00\x42\x32Z0github.com/seek-ret/public-protobuf/protogo/authb\x06proto3'
)




_CLIENTCREDENTIALS = _descriptor.Descriptor(
  name='ClientCredentials',
  full_name='seekret.auth.ClientCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='seekret.auth.ClientCredentials.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_secret', full_name='seekret.auth.ClientCredentials.client_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=108,
)


_JWTDETAILS = _descriptor.Descriptor(
  name='JWTDetails',
  full_name='seekret.auth.JWTDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='seekret.auth.JWTDetails.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refresh_token', full_name='seekret.auth.JWTDetails.refresh_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=167,
)


_CLIENTAUTHENTICATEREQUEST = _descriptor.Descriptor(
  name='ClientAuthenticateRequest',
  full_name='seekret.auth.ClientAuthenticateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_credentials', full_name='seekret.auth.ClientAuthenticateRequest.client_credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=257,
)


_CLIENTAUTHENTICATERESPONSE = _descriptor.Descriptor(
  name='ClientAuthenticateResponse',
  full_name='seekret.auth.ClientAuthenticateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='seekret.auth.ClientAuthenticateResponse.details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=330,
)

_CLIENTAUTHENTICATEREQUEST.fields_by_name['client_credentials'].message_type = _CLIENTCREDENTIALS
_CLIENTAUTHENTICATERESPONSE.fields_by_name['details'].message_type = _JWTDETAILS
DESCRIPTOR.message_types_by_name['ClientCredentials'] = _CLIENTCREDENTIALS
DESCRIPTOR.message_types_by_name['JWTDetails'] = _JWTDETAILS
DESCRIPTOR.message_types_by_name['ClientAuthenticateRequest'] = _CLIENTAUTHENTICATEREQUEST
DESCRIPTOR.message_types_by_name['ClientAuthenticateResponse'] = _CLIENTAUTHENTICATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCredentials = _reflection.GeneratedProtocolMessageType('ClientCredentials', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCREDENTIALS,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.auth.ClientCredentials)
  })
_sym_db.RegisterMessage(ClientCredentials)

JWTDetails = _reflection.GeneratedProtocolMessageType('JWTDetails', (_message.Message,), {
  'DESCRIPTOR' : _JWTDETAILS,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.auth.JWTDetails)
  })
_sym_db.RegisterMessage(JWTDetails)

ClientAuthenticateRequest = _reflection.GeneratedProtocolMessageType('ClientAuthenticateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTAUTHENTICATEREQUEST,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.auth.ClientAuthenticateRequest)
  })
_sym_db.RegisterMessage(ClientAuthenticateRequest)

ClientAuthenticateResponse = _reflection.GeneratedProtocolMessageType('ClientAuthenticateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTAUTHENTICATERESPONSE,
  '__module__' : 'seekret.proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:seekret.auth.ClientAuthenticateResponse)
  })
_sym_db.RegisterMessage(ClientAuthenticateResponse)


DESCRIPTOR._options = None

_AUTH = _descriptor.ServiceDescriptor(
  name='Auth',
  full_name='seekret.auth.Auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=332,
  serialized_end=445,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClientAuthenticate',
    full_name='seekret.auth.Auth.ClientAuthenticate',
    index=0,
    containing_service=None,
    input_type=_CLIENTAUTHENTICATEREQUEST,
    output_type=_CLIENTAUTHENTICATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['Auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
