# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from seekret.proto.auth import auth_pb2 as seekret_dot_proto_dot_auth_dot_auth__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientAuthenticate = channel.unary_unary(
                '/seekret.auth.Auth/ClientAuthenticate',
                request_serializer=seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateRequest.SerializeToString,
                response_deserializer=seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateResponse.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientAuthenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientAuthenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientAuthenticate,
                    request_deserializer=seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateRequest.FromString,
                    response_serializer=seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seekret.auth.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientAuthenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seekret.auth.Auth/ClientAuthenticate',
            seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateRequest.SerializeToString,
            seekret_dot_proto_dot_auth_dot_auth__pb2.ClientAuthenticateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
